sudo: false

language: node_js
node_js:
  - "10"

jobs:
  include:
    - stage: build
      script: yarn install && yarn build
    - stage: deploy
      before_install:
        - openssl aes-256-cbc -K $encrypted_7c7c680ab1be_key -iv $encrypted_7c7c680ab1be_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
      install:
        - sh ./.travis/config_ssh.sh
      script: yarn install && yarn build --prod=true && sh ./.travis/deploy.sh

stages:
  - name: deploy
    if: type = push AND branch = master
  - name: build
    if: type = pull_request AND branch = master
